version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wemall
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: changeme
      DB_NAME: wemall
      JWT_SECRET: please-change
      JWT_EXPIRES_IN: 7d
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql-data:
